services:
  db:
    image: postgres:16-alpine
    container_name: welltrack-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: welltrack
      POSTGRES_PASSWORD: welltrack
    volumes:
      - welltrack-data:/var/lib/postgresql/data

volumes:
  welltrack-data:
